//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_state
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_state()
        {
            this.accounts = new HashSet<account>();
        }
    
        public short ACCOUNT_STATE_ID { get; set; }
        public int LOOKUP_ID { get; set; }
        public short PRD_TYPE_ID { get; set; }
        public short CURRENTLY_IN_USE { get; set; }
        public string STATUS_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        public virtual lookup_value lookup_value { get; set; }
    }
}
