//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.loan_account = new HashSet<loan_account>();
            this.loan_schedule = new HashSet<loan_schedule>();
            this.rec_payment = new HashSet<rec_payment>();
        }
    
        public int ACCOUNT_ID { get; set; }
        public string GLOBAL_ACCOUNT_NUM { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<short> ACCOUNT_STATE_ID { get; set; }
        public short ACCOUNT_TYPE_ID { get; set; }
        public Nullable<short> OFFICE_ID { get; set; }
        public Nullable<short> PERSONNEL_ID { get; set; }
        public short CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<short> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> VERSION_NO { get; set; }
        public short OFFSETTING_ALLOWABLE { get; set; }
        public string EXTERNAL_ID { get; set; }
        public Nullable<short> Last_personnel_id { get; set; }
        public Nullable<System.DateTime> ACCOUNT_CREATED_DATE { get; set; }
    
        public virtual account_state account_state { get; set; }
        public virtual personnel personnel { get; set; }
        public virtual office office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_account> loan_account { get; set; }
        public virtual loan_account loan_account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_schedule> loan_schedule { get; set; }
        public virtual customer customer { get; set; }
        public virtual rec_collection rec_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rec_payment> rec_payment { get; set; }
    }
}
