//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_detail
    {
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> ethnicity { get; set; }
        public Nullable<int> CITIZENSHIP { get; set; }
        public Nullable<int> HANDICAPPED { get; set; }
        public Nullable<int> BUSINESS_ACTIVITIES { get; set; }
        public Nullable<int> MARITAL_STATUS { get; set; }
        public Nullable<int> EDUCATION_LEVEL { get; set; }
        public Nullable<short> NUM_CHILDREN { get; set; }
        public Nullable<short> GENDER { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
        public string HANDICAPPED_DETAILS { get; set; }
        public Nullable<int> POVERTY_STATUS { get; set; }
        public Nullable<decimal> POVERTY_LHOOD_PCT { get; set; }
    
        public virtual lookup_value lookup_value { get; set; }
        public virtual lookup_value lookup_value1 { get; set; }
        public virtual lookup_value lookup_value2 { get; set; }
        public virtual lookup_value lookup_value3 { get; set; }
        public virtual lookup_value lookup_value4 { get; set; }
        public virtual lookup_value lookup_value5 { get; set; }
        public virtual customer customer { get; set; }
    }
}
