//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_flag_detail
    {
        public int CUSTOMER_FLAG_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public short FLAG_ID { get; set; }
        public Nullable<short> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> VERSION_NO { get; set; }
    
        public virtual customer_state_flag customer_state_flag { get; set; }
        public virtual personnel personnel { get; set; }
        public virtual customer customer { get; set; }
    }
}
