//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_name_detail
    {
        public int CUSTOMER_NAME_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<short> NAME_TYPE { get; set; }
        public Nullable<short> LOCALE_ID { get; set; }
        public Nullable<int> SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SECOND_LAST_NAME { get; set; }
        public string SECOND_MIDDLE_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
    
        public virtual lookup_value lookup_value { get; set; }
        public virtual customer customer { get; set; }
    }
}
