//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.accounts = new HashSet<account>();
            this.customer_address_detail = new HashSet<customer_address_detail>();
            this.customer_flag_detail = new HashSet<customer_flag_detail>();
            this.customer1 = new HashSet<customer>();
            this.customer_name_detail = new HashSet<customer_name_detail>();
            this.customer_note = new HashSet<customer_note>();
            this.loan_schedule = new HashSet<loan_schedule>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public short CUSTOMER_LEVEL_ID { get; set; }
        public string GLOBAL_CUST_NUM { get; set; }
        public Nullable<short> LOAN_OFFICER_ID { get; set; }
        public Nullable<short> CUSTOMER_FORMEDBY_ID { get; set; }
        public Nullable<short> STATUS_ID { get; set; }
        public Nullable<short> BRANCH_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SECOND_LAST_NAME { get; set; }
        public string DISPLAY_ADDRESS { get; set; }
        public string EXTERNAL_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<short> GROUP_FLAG { get; set; }
        public Nullable<short> TRAINED { get; set; }
        public Nullable<System.DateTime> TRAINED_DATE { get; set; }
        public Nullable<int> PARENT_CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string SEARCH_ID { get; set; }
        public Nullable<int> MAX_CHILD_COUNT { get; set; }
        public Nullable<short> HO_UPDATED { get; set; }
        public Nullable<short> CLIENT_CONFIDENTIAL { get; set; }
        public Nullable<System.DateTime> MFI_JOINING_DATE { get; set; }
        public string GOVERNMENT_ID { get; set; }
        public Nullable<System.DateTime> CUSTOMER_ACTIVATION_DATE { get; set; }
        public Nullable<short> CREATED_BY { get; set; }
        public Nullable<short> UPDATED_BY { get; set; }
        public Nullable<short> BLACKLISTED { get; set; }
        public string DISCRIMINATOR { get; set; }
        public int VERSION_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_detail> customer_address_detail { get; set; }
        public virtual customer_detail customer_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_flag_detail> customer_flag_detail { get; set; }
        public virtual customer_state customer_state { get; set; }
        public virtual office office { get; set; }
        public virtual personnel personnel { get; set; }
        public virtual personnel personnel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer1 { get; set; }
        public virtual customer customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_name_detail> customer_name_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_note> customer_note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_schedule> loan_schedule { get; set; }
    }
}
