//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookup_value_locale
    {
        public int LOOKUP_VALUE_ID { get; set; }
        public short LOCALE_ID { get; set; }
        public int LOOKUP_ID { get; set; }
        public string LOOKUP_VALUE { get; set; }
    
        public virtual lookup_value lookup_value1 { get; set; }
    }
}
