//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrEntitiesConnection : DbContext
    {
        public hrEntitiesConnection()
            : base("name=hrEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<timesheetyear2016> timesheetyear2016 { get; set; }
        public virtual DbSet<timesheetreason> timesheetreasons { get; set; }
        public virtual DbSet<timesheetpresent> timesheetpresents { get; set; }
    }
}
