//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mifosEntitiesConnection : DbContext
    {
        public mifosEntitiesConnection()
            : base("name=mifosEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<account_state> account_state { get; set; }
        public virtual DbSet<customer_address_detail> customer_address_detail { get; set; }
        public virtual DbSet<customer_detail> customer_detail { get; set; }
        public virtual DbSet<customer_flag_detail> customer_flag_detail { get; set; }
        public virtual DbSet<customer_name_detail> customer_name_detail { get; set; }
        public virtual DbSet<customer_note> customer_note { get; set; }
        public virtual DbSet<customer_state_flag> customer_state_flag { get; set; }
        public virtual DbSet<loan_account> loan_account { get; set; }
        public virtual DbSet<loan_schedule> loan_schedule { get; set; }
        public virtual DbSet<lookup_value> lookup_value { get; set; }
        public virtual DbSet<lookup_value_locale> lookup_value_locale { get; set; }
        public virtual DbSet<office> offices { get; set; }
        public virtual DbSet<personnel> personnels { get; set; }
        public virtual DbSet<prd_offering> prd_offering { get; set; }
        public virtual DbSet<customer_state> customer_state { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<rec_entity> rec_entity { get; set; }
        public virtual DbSet<rec_lookupvalue> rec_lookupvalue { get; set; }
        public virtual DbSet<rec_collection> rec_collection { get; set; }
        public virtual DbSet<rec_payment> rec_payment { get; set; }
    }
}
