//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public office()
        {
            this.accounts = new HashSet<account>();
            this.office1 = new HashSet<office>();
            this.personnels = new HashSet<personnel>();
            this.prd_offering = new HashSet<prd_offering>();
            this.customers = new HashSet<customer>();
        }
    
        public short OFFICE_ID { get; set; }
        public string GLOBAL_OFFICE_NUM { get; set; }
        public short OFFICE_LEVEL_ID { get; set; }
        public string SEARCH_ID { get; set; }
        public int MAX_CHILD_COUNT { get; set; }
        public short LOCAL_REMOTE_FLAG { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<short> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<short> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string OFFICE_SHORT_NAME { get; set; }
        public Nullable<short> PARENT_OFFICE_ID { get; set; }
        public short STATUS_ID { get; set; }
        public int VERSION_NO { get; set; }
        public Nullable<short> OFFICE_CODE_ID { get; set; }
        public Nullable<int> p_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<office> office1 { get; set; }
        public virtual office office2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel> personnels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prd_offering> prd_offering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
    }
}
