//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_offering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prd_offering()
        {
            this.loan_account = new HashSet<loan_account>();
        }
    
        public short PRD_OFFERING_ID { get; set; }
        public short PRD_APPLICABLE_MASTER_ID { get; set; }
        public string GLOBAL_PRD_OFFERING_NUM { get; set; }
        public short PRD_CATEGORY_ID { get; set; }
        public Nullable<short> PRD_TYPE_ID { get; set; }
        public Nullable<short> OFFICE_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> GLCODE_ID { get; set; }
        public string PRD_OFFERING_NAME { get; set; }
        public string PRD_OFFERING_SHORT_NAME { get; set; }
        public Nullable<short> OFFERING_STATUS_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<int> VERSION_NO { get; set; }
        public Nullable<short> PRD_MIX_FLAG { get; set; }
        public Nullable<short> CURRENCY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_account> loan_account { get; set; }
        public virtual office office { get; set; }
    }
}
