//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class rec_collection
    {
        public int Account_id { get; set; }
        public int CollOrLegal { get; set; }
        public int Type { get; set; }
        public System.DateTime DateOfTransfer { get; set; }
        public decimal amount { get; set; }
        public int TypeFollowup { get; set; }
    
        public virtual account account { get; set; }
        public virtual rec_lookupvalue rec_lookupvalue { get; set; }
        public virtual rec_lookupvalue rec_lookupvalue1 { get; set; }
        public virtual rec_lookupvalue rec_lookupvalue2 { get; set; }
    }
}
