//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheetyear2016
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheetyear2016()
        {
            this.timesheetpresents = new HashSet<timesheetpresent>();
        }
    
        public int CalenderID { get; set; }
        public Nullable<System.DateTime> GlobalDate { get; set; }
        public Nullable<int> DayOfMonthId { get; set; }
        public Nullable<int> DayOfWeekId { get; set; }
        public string DayName { get; set; }
        public Nullable<int> MonthId { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<bool> Isholiday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheetpresent> timesheetpresents { get; set; }
    }
}
