//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchClientWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheetpresent
    {
        public int attendanceID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> CalenderID { get; set; }
        public bool IsPresent { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Note { get; set; }
        public bool Approved { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual timesheetyear2016 timesheetyear2016 { get; set; }
        public virtual timesheetreason timesheetreason { get; set; }
    }
}
